Pass the `hosted-url` to PackageAnalyzer, read `PUB_HOSTED_URL` env f…
dart-lang/pana pull request #1032
Opened 2022-03-09 09:14 UTC by talisk

…rom environment in `computeOutdatedVersions` for the self-hosted pub dependencies. (#1031)

2022-03-10 16:54 UTC, isoos requested changes

2022-03-10 16:54 UTC, isoos commented on lib/src/report/dependencies.dart
> +      environmentUri = Uri.parse(hostUrlString);
`environmentUri = Uri.tryParse(hostUrlString);`
and let's drop the try-catch, as we in general don't like generic catch blocks, and the `environmentUri = null` is not needed either.

2022-03-16 09:09 UTC, talisk commented
@isoos I was wondering if you could review again. :)

2022-03-16 13:44 UTC, jonasfj approved these changes

2022-03-16 14:25 UTC, merged